#!/bin/sh

AUTHOR=$(git config user.name)
ROOT=$(git rev-parse --show-toplevel)

case "$AUTHOR" in
    "marenkalberer")
        SOUND="maren.wav"
        ;;
    "destroyo123")
        SOUND="etan.wav"
        ;;
    *)
        exit 0
        ;;
esac

FULL_PATH="$ROOT/sounds/$SOUND"
OS="$(uname -s)"

if [ "$OS" = "Darwin" ]; then
    bash "$ROOT/scripts/play-sound.sh" "$FULL_PATH"
else
    powershell.exe -ExecutionPolicy Bypass -File "$ROOT/scripts/play-sound.ps1" "$FULL_PATH"
fi