#!/bin/sh

DEBUG=false

AUTHOR=$(git config user.name)
ROOT=$(git rev-parse --show-toplevel)

if [ "$DEBUG" = true ]; then
    echo "AUTHOR=$AUTHOR" >> "$ROOT/hook-debug.txt"
fi

case "$AUTHOR" in
    "marenkalberer")
        SOUND="maren.wav"
        ;;
    "destroyo123")
        SOUND="etan.wav"
        ;;
    *)
        exit 0
        ;;
esac

FULL_PATH="$ROOT/sounds/$SOUND"

OS="$(uname -s)"

if [ "$OS" = "Darwin" ]; then
    afplay "$FULL_PATH"
else
    powershell.exe -c "(New-Object System.Media.SoundPlayer '$FULL_PATH').PlaySync();"
fi